version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mqtt

  frontend:
    build: ./frontend
    ports:
      - "80:80"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
